functional:
1. Пользователь должен иметь возможность искать товары по ключевому слову или категории
2. Пользователь должен иметь возможность фильтровать товары
3. Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
4. Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
1. Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
2. Сайт должен быть безопасным и защищать данные пользователя
3. Сайт должен иметь мобильную версию
4. Сайт нужно протестировать на совместимость с последними версиями браузеров
5. Важно, чтобы сайт мог обрабатывать большое количество трафика
6. Сайт должен быть доступен на различных устройствах
implicit:
1. Сайт должен иметь кнопку "фильтр"
2. Сайт должен иметь кнопку "корзина"
3. У каждого товара сайта должна быть кликабельна кнопка "добавить в корзину"
4. Корзина должна иметь кнопку "удаление товара"
5. Основная страница сайта должна иметь окно "поиск"
6. Вводимые значения в строке поиск должны соответствовать запросу по категории
7. Кнопка перемещения между разделами должна перемещать в соответствии с запросом
