---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- Сайт должен иметь кнопку "фильтр"
- Сайт должен иметь кнопку "корзина"
- У каждого товара сайта должна быть кликабельна кнопка "добавить в корзину"
- Корзина должна иметь кнопку "удаление товара"
- Основная страница сайта должна иметь окно "поиск"
- Вводимые значения в строке поиск должны соответствовать запросу по категории
- Кнопка перемещения между разделами должна перемещать в соответствии с запросом
- Сайт должен предоставлять возможность регистрации новых пользователей
- Сайт должен предоставлять возможность входа в личный кабинет для зарегистрированных пользователей
- Кнопка "Категория" должна содержать вс ебе выбор всех имеющихся категорий
